"""bookmarks tablosu eklendi

Revision ID: 451eeffa37c5
Revises: 0002
Create Date: 2026-08-13 07:09:13.980913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '451eeffa37c5'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT: ioc_type_enum tipi zaten 0001'de olusturuldu; burada tekrar
    # CREATE TYPE denenmesin diye create_type=False kullaniliyor.
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column(
        'ioc_type',
        postgresql.ENUM('ip', 'domain', 'url', 'hash', name='ioc_type_enum', create_type=False),
        nullable=False,
    ),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_value'), 'bookmarks', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_value'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
